### ISSUE TITLE
Sort "orderedLengthFreqs" in Mendenhall

### ISSUE THREAD

**Issue by christofs** [sgsinclair/epistemologica#1]
At least with my version of Python (3.6.7), the variable "orderLengthFreqs" in code cell 13 does not get sorted by default, but requires an additional "sorted" to be added. Like so: 

```
lengthFreqs = nltk.FreqDist(lengths)
orderedLengthFreqs = sorted(list(lengthFreqs.items()))
```
Otherwise, the graph get's all scrambled up and the phrase "not bad!" below receives an ironic reading. :-)

**Comment by GeoffreyRockwell** [comment]
Dear Matt,

Thanks for this. Stéfan and I will take a look at it. I’m sure you are right.

Best,

Geoffrey R.

**Comment by sgsinclair** [comment]
Curious, I wonder if the behaviour of FreqDist has changed (and if so how many other things are now broken in the materials we've written). Anyway, thanks very much for pointing this out!

https://github.com/sgsinclair/epistemologica/commit/fec4d374da25c0c9e8730d32da81cc481aa397fa
